flysystem:
    storages:
        default.storage:
            adapter: 'aws'
            options:
                client: Aws\S3\S3Client
                bucket: '%env(AWS_S3_BUCKET_NAME)%'
                prefix: '%env(resolve:PREFIX)%'