App\Entity\Maker:
  attributes:
    normalization_context:
      groups: [maker_read]
  collectionOperations:
    get:
    create:
      method: POST
      path: /maker/create
      controller: App\Api\Action\Maker\Create
      denormalization_context:
        groups: [maker_post]
      openapi_context:
        summary: Create a new vehicle's model maker
  itemOperations:
    get:
      method: GET
    put:
      method: PUT
      denormalization_context:
        groups: [maker_update]
    delete:
      method: DELETE
  properties: 
    models: 
      subresource:
        resourceClass: App\Entity\Model
        collection: true
        maxDepth: 1
        
