App\Entity\Vehicle:
  attributes:
    normalization_context:
      groups: [vehicle_read]
  collectionOperations:
    create:
      method: POST
      path: /vehicle/create
      controller: App\Api\Action\Vehicle\Create
      denormalization_context:
        groups: [vehicle_post]
      openapi_context:
        summary: Create a new Vehicle
  itemOperations:
    get:
      method: GET
    put:
      method: PUT
      denormalization_context:
        groups: [vehicle_update]