App\Entity\Maker:
  attributes:
    id:
      groups: [maker_read]
    name:
      groups: [maker_read, maker_post, model_read]
    moodels:
      groups: [maker_read, maker_post]
    createdAt:
      groups: [maker_read]
    updatedAt:
      groups: [maker_read]
