App\Entity\Vehicle:
  attributes:
    id:
      groups: [vehicle_read]
    plateNumber:
      groups: [vehicle_read, vehicle_post, vehicle_update]
    modelYear:
      groups: [vehicle_read, vehicle_post, vehicle_update]
    model:
      groups: [vehicle_read]
    createdAt:
      groups: [vehicle_read]
    updatedAt:
      groups: [vehicle_read]
